### ISSUE TITLE
Вопрос по "Библиотеке PKCS#11" для токена

### ISSUE THREAD

**Issue by minherc** [a513/CryptoArmPKCS#2]
Добрый день!
Вопрос: а где можно взять эту библиотеку?
Скачал тут http://soft.lissi.ru/downloads/pkcs11_libs/pkcs11_libs_win/
не заработала, попробовал там все длл'ки 
конфиг: windows 10, рутокен 

update: как прочитать локальные сертификаты из реестра?
Может справку какую сделать для этого приложения, приложение очень хорошее, странно что не очень популярное...

**Comment by minherc** [comment]
_Ответ :)_ 
Найти поиском в системе (если уже стоят криптопровайдеры)

_Файл для поиска:_
rtPKCS11.dll

_Библиотека rtPKCS11 предназначена для работы в Windows как с Рутокен S, так и с Рутокен Lite и ЭЦП PKI/2.0/3.0. Она реализует функциональность зарубежных криптографических алгоритмов (RSA)._ [подробнее](https://dev.rutoken.ru/pages/viewpage.action?pageId=3178509)

В win 10 нашлось в следующих местах:
![image](https://user-images.githubusercontent.com/6546280/182015355-b884037b-ec8d-4e0c-b2ef-ecec778add41.png)

С программой заработала только 1 ддл'ка, которая находиться в \system32\

На токене, который есть в наличии, все сертификаты просрочены, возможно поэтому выбрать их не могу (поле сертификат пустое. Так и должно быть?)

Остался открытым вопрос:
**Как подписать документ из реестра или из файла?** 
(понятно что из файла, не по феншую, но часто очень надо))

**Comment by a513** [comment]
Скажите, какую задачу вы хотите решить? 
Утилита работает либо с токенами PKCS#11, поддерживающими российскик криптоалгориты либо с PKCS#12.
Токены типа  RuToken Lite это фактически флэшка.
Для работы с реестром - читайте доку ао Винде.

P.S. А что за библиотку вы хотели скачать и с какой целью.
За  добрые слова спасибо. Да, и пишите лучше на почту : vorlov@lissi.ru

**Comment by minherc** [comment]
Спасибо за быстрый ответ!

Написал вам на почту
